---
'á': a
'é': e
'í': i
'ó': o
'ú': u
'Á': A
'É': E
'Í': I
'Ó': O
'Ú': U
'â': a
'ê': e
'î': i
'ô': o
'û': u
'Â': A
'Ê': E
'Î': I
'Ô': O
'Û': U
'ã': a
'ẽ': e
'ĩ': i
'õ': o
'ũ': u
'Ã': A
'Ẽ': E
'Ĩ': I
'Õ': O
'Ũ': U
'ä': a
'ë': e
'ï': i
'ö': o
'ü': u
'Ä': A
'Ë': E
'Ï': I
'Ö': O
'Ü': U
'à': a
'è': e
'ì': i
'ò': o
'ù': u
'À': A
'È': E
'Ì': I
'Ò': O
'Ù': U
'ç': ç
'Ç': Ç