module Features

  USER_MANAGE_STATUS      = 'USER_MANAGE_STATUS'
  USER_CREATE_ACCOUNT     = 'USER_CREATE_ACCOUNT'
  USER_DELETE_ACCOUNT     = 'USER_DELETE_ACCOUNT'
  USER_MANAGE_PERMISSIONS = 'USER_MANAGE_PERMISSIONS'

end