module Rules

  WATCHER                 = 'WATCHER'
  
  USER_MANAGE_STATUS      = 'USER_MANAGE_STATUS'
  USER_CREATE_ACCOUNT     = 'USER_CREATE_ACCOUNT'
  USER_DELETE_ACCOUNT     = 'USER_DELETE_ACCOUNT'
  USER_MANAGE_PERMISSIONS = 'USER_MANAGE_PERMISSIONS'
  
  GROUP_CREATE_GROUP      = 'GROUP_CREATE_GROUP'
  GROUP_DELETE_GROUP      = 'GROUP_DELETE_GROUP'

end